export const FETCH_EVENTS_DATA = 'FETCH_EVENTS_DATA';
export const FETCH_TOPICNAMES_DATA = 'FETCH_TOPICNAMES_DATA';


export const ADD_EVENT = 'ADD_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
//
export const SET_NAME = 'SET_NAME';
export const SET_CITY = 'SET_CITY';
export const SET_DATE = 'SET_DATE';
export const SET_TIME_START = 'SET_TIME_START';
export const SET_TIME_END = 'SET_TIME_END';
export const SET_SELECTED_TOPIC = 'SET_SELECTED_TOPIC';

//// FILTER
export const FETCH_CURRENTFILTERS_DATA = 'FETCH_CURRENTFILTERS_DATA';
export const ADD_CUSTOM_FILTER = 'ADD_CUSTOM_FILTER';
export const ADD_FILTER_LIST = 'ADD_FILTER_LIST';
export const DELETE_CUSTOM_FILTER = 'DELETE_CUSTOM_FILTER';
export const SEARCH_CUSTOM_FILTER = 'SEARCH_CUSTOM_FILTER';
//
export const SET_CITY_FILTER = 'SET_CITY_FILTER';
export const SET_DATE_FILTER = 'SET_DATE_FILTER';
export const SET_TIME_FILTER = 'SET_TIME_FILTER';
export const SET_TOPIC_FILTER = 'SET_TOPIC_FILTER';
export const DISABLE_SAVE_FILTER_BUTTON = 'DISABLE_SAVE_FILTER_BUTTON';
